config/routes.rb
Splurty::Application.routes.draw do

  root 'categories#index'
  
  resources :categories do
    resources :quotes
  end
  
  get 'about', :to => 'quotes#about'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :quotes
  accepts_nested_attributes_for :quotes
  validates :title, :presence => true, :length  => { :maximum => 140, :minimum => 3 }
  
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :saying, :presence => true, :length  => { :maximum => 140, :minimum => 3 }
  validates :author, :presence => true, :length => { :maximum => 50, :minimum => 3 }
  belongs_to :category

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @category = Category.order("RANDOM()").first
    @quote = Quote.new
  end

  def show
    @category = Category.find(params[:id])
    @quotes = @category.quotes.all
  end

  def update
    @category = Category.find(params[:id])
    @new_quote = @category.quotes.build
    
    if @new_quote.save
      render :index
    else
      @category = Category.order("RANDOM()").first
      render :index, :status => :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:title, quotes_attributes: [:saying, :author])
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  #before_action :set_category, only: [:index]

  def index
    @category = Category.order("RANDOM()").first
    @quote = @category.quotes
  end


  def create
    @category = Category.find(params[:category_id])
    @new_quote = Quotes.create(quote_params)

    if @new_quote.invalid?
      @category = Category.order("RANDOM()").first
      render :index, :status => :unprocessable_entity
    else
      @quote = @new_quote
      redirect_to @category.quotes
    end

  end

  def about
  end

  private


  def set_category
    @category = Category.find(params[:category_id])
  end

  def quote_params
    params.require(:quote).permit(:saying, :author, :category_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/categories/_quote_fields.html.erb
<div class="nested-fields">
  <%= f.input :saying, :label => "What do you want to say?", :placeholder => "Inspire us!" %>
  <br />
  <%= f.input :author, :label => "Who said it?", :placeholder => "Cite your source" %>
  <br />
</div>
    

app/views/categories/index.html.erb
<h2>
  <span>Inspiring Quotes for:</span>
  <h1><%= link_to @category.title, category_quotes_path(@category) %></h1>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title>Quoteable!</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="col-xs-3">
      <%= link_to root_path, :class => 'logo' do %>
        <div class="circle">
        <br />
        Be brave
        <br />
        Be strong
        <br />
        Don't quit
      </div>
      <% end %>
    </div>
    <div class="col-sm-4 hidden-xs slogan">
      Giving inspiration for the temporarily enslaved.
    </div>
    <div class="col-xs-8 col-xs-offset-1 col-sm-offset-0 col-sm-5 links">
     <%= link_to 'Contribute', '#', :id => 'contribute_link', :data => {:toggle => 'modal', :target => '#myModal'} %>
     &nbsp;&nbsp;
      <%= link_to 'About', about_path %>
    </div>
  </header>

      <!-- Button trigger modal -->
  

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Add a quote, player</h4>
        </div>
       <%= simple_form_for @category do |f| %>
          <div class="modal-body">
            <%= f.input :title, as: :dropdown_select, collection: @category_titles, :label => "Quote Category", :include_blank => false %> 
            <%= f.simple_fields_for :quotes do |quote| %>
              <%= render 'quote_fields', :f => quote %>
              <% end %>
            
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit 'Add Quote', :class => 'btn btn-danger' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <hr />
  <br class="clear" />

  <div class="container">
      <% if flash[:error].present? %>
      <div class="col-xs-10 col-xs-offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>
    <%= yield %>
  </div>

  <div class="footer">
    <div class="container">
      <div class="col-xs-12 col-sm-6">
        <%= link_to "This quote bores me! I need a new one.", root_path, :class => 'next-quote' %>
      </div>
      <div class="col-xs-12 col-sm-6 footer-blurb">
        Made in the Chestah! by Big Tate Price aka Voltron</a><br />
        Feel better. Get Better.</a>
      </div>

      <% if @new_quote.present? && @new_quote.errors.present? %>
        <script>
        $(function() {
          $('#contribute_link').click();
        });
        </script>
      <% end %>

</body>
</html>

app/views/quotes/_new.html.erb
<div class="nested-fields">
  <%= f.input :saying, :label => "What do you want to say?", :placeholder => "Inspire us!" %>
  <br />
  <%= f.input :author, :label => "Who said it?", :placeholder => "Cite your source" %>
  <br />
  

app/views/quotes/_quote_fields.html.erb
<div class="nested-fields">
  <%= f.input :saying, :label => "What do you want to say?", :placeholder => "Inspire us!" %>
  <br />
  <%= f.input :author, :label => "Who said it?", :placeholder => "Cite your source" %>
  <br />
</div>
    

app/views/quotes/about.html.erb
<div class="col-xs-10 col-xs-offset-1 about">
  <h1>About Quoteable!</h1>
    <p>
    What is this place? What does Splurty mean? What the hell is a unicorn?
  </p>
  <br />
  <p>
    <a target="_blank" href="http://github.com/priceat">Tate Price</a> does not know. Tate Price does not care. Rather, he wants to create a place for you to find inspirational quotes and save them... for those rainy days!
  </p>
  <p>
    Get tagging, friendo.
  </p>

    <div class="col-xs-12 col-sm-4">
    <%= image_tag 'voltron.jpg', :class => 'img-responsive' %>
  </div>

  <div class="col-xs-12 col-sm-7 col-sm-offset-1">
    <h2 class="text-center">Tate Price aka Tatetron</h2>
    <br />
    <p>
      Tate Price is just like you.... Except not. He is more like water. Responsive, agile and flexible. Long ago he learned there is very little difference between salaried work and indentured slavery. He resolved to change himself. Adding skills, experiences and abilities. Like Voltron. Soon he will be fully transformed... and ready to do battle. 
    </p>
  </div>

</div>

<br class="clear" />
<br />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<h2>
   <span>Inspiring Quotes for:</span>
  <h1><%= @category.title %></h1>
  <% @category.quotes.each do |quote| %>
<h2><%= quote.saying %></h2>
<h2 class="pull-right">- <%= quote.author %></h2>
<% end %>

<br class="clear" />
<br />
<br />
<br />
<%= link_to 'Back', :back %> 